export function getApp2Js() {
  return `const NL='\\n';
window.__APP2_READY=true;console.log('app2.js ready');
class BINLookup{constructor(){this.currentResults=[];this.currentPage=0;this.filters={};this.cardExporter={bins:[],cancelExport:false};this.init();}
async init(){await this.loadFilters();this.setupEventListeners();this.loadDashboard(true);}
setupEventListeners(){const safe=(id,ev,fn)=>{const el=document.getElementById(id);if(el)el.addEventListener(ev,fn)};document.querySelectorAll('.tab-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));btn.classList.add('active');const tab=btn.dataset.tab;const t=document.getElementById(tab);if(t)t.classList.add('active');if(tab==='dashboard')this.loadDashboard();});});safe('searchBtn','click',()=>this.search());safe('clearBtn','click',()=>this.clearFilters());safe('copyBinsBtn','click',()=>this.copyBinsList());safe('prevBtn','click',()=>this.previousPage());safe('nextBtn','click',()=>this.nextPage());safe('pageJumpBtn','click',()=>this.jumpToPage());safe('refreshDash','click',()=>this.loadDashboard(true));safe('normalizeBtn','click',()=>this.normalize());safe('copyNorm','click',()=>this.copy('normalizeOutput'));safe('dupBtn','click',()=>this.checkDup());safe('dupFileBtn','click',()=>{const f=document.getElementById('dupFileInput');if(f)f.click()});safe('dupFileInput','change',(e)=>this.handleDupFileUpload(e));safe('copyDup','click',()=>this.copy('dupOutput'));safe('importBtn','click',()=>this.import());safe('importFileBtn','click',()=>{const f=document.getElementById('importFileInput');if(f)f.click()});safe('importFileInput','change',(e)=>this.handleFileUpload(e));safe('searchBinsBtn','click',()=>this.searchBinsForExport());safe('clearCardFiltersBtn','click',()=>this.clearCardFilters());safe('exportAllBtn','click',()=>this.startExport());safe('cancelExportBtn','click',()=>this.cancelExport());safe('copyExportBtn','click',()=>this.copy('exportOutput'));safe('downloadExportBtn','click',()=>this.downloadExport());['Enter'].forEach(key=>{const b=document.getElementById('binInput');if(b)b.addEventListener('keypress',e=>{if(e.key===key)this.search()});const pj=document.getElementById('pageJumpInput');if(pj)pj.addEventListener('keypress',e=>{if(e.key===key)this.jumpToPage()});});['normalizeInput','dupInput','importInput'].forEach(id=>{const el=document.getElementById(id);if(el){el.addEventListener('paste',()=>{setTimeout(()=>{el.scrollLeft=0},50);});const valueProp=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value');if(valueProp){const originalSet=valueProp.set;Object.defineProperty(el,'value',{set:function(val){originalSet.call(this,val);setTimeout(()=>{this.scrollLeft=0},50);},get:valueProp.get,configurable:true});}}});}
async loadFilters(){try{const r=await fetch('/api/filters');const d=await r.json();if(d.success){const lists={brands:d.data.brands,types:d.data.types,categories:d.data.categories,countries:d.data.countries,issuers:d.data.issuers};['brands','types','categories','countries','issuers'].forEach(key=>{const datalist=document.getElementById(key+'-list');if(datalist)(lists[key]||[]).forEach(v=>{const opt=document.createElement('option');opt.value=v;datalist.appendChild(opt);});});const brandSelect=document.getElementById('cardBrandFilter');const typeSelect=document.getElementById('cardTypeFilter');const categorySelect=document.getElementById('cardCategoryFilter');const countrySelect=document.getElementById('cardCountryFilter');(lists.brands||[]).forEach(v=>{const opt=document.createElement('option');opt.value=v;opt.textContent=v;brandSelect.appendChild(opt);});(lists.types||[]).forEach(v=>{const opt=document.createElement('option');opt.value=v;opt.textContent=v;typeSelect.appendChild(opt);});(lists.categories||[]).forEach(v=>{const opt=document.createElement('option');opt.value=v;opt.textContent=v;categorySelect.appendChild(opt);});(lists.countries||[]).forEach(v=>{const opt=document.createElement('option');opt.value=v;opt.textContent=v;countrySelect.appendChild(opt);});}}catch(e){console.error('Load filters error:',e)}}
getSearchParams(){const params={};const bin=document.getElementById('binInput').value.trim();if(bin)params.bin=bin.split(/[\\n,]/).filter(b=>b.trim()).join(',');['brand','type','category','country','issuer'].forEach(k=>{const v=document.getElementById(k+'Filter').value.trim();if(v)params[k]=v;});params.limit=parseInt(document.getElementById('limitInput').value)||50;params.offset=this.currentPage*params.limit;return params;}
async search(){const btn=document.getElementById('searchBtn');const html=btn.innerHTML;btn.disabled=true;btn.innerHTML='<div class="loading inline-block mr-2"></div>Searching...';this.showLoading();try{const params=this.getSearchParams();const qs=new URLSearchParams(params).toString();const r=await fetch('/api/bin?'+qs);const d=await r.json();if(d.success){this.currentResults=d.data;this.displayResults();this.updatePagination(d.pagination);setTimeout(()=>document.getElementById('resultsBody').scrollIntoView({behavior:'smooth',block:'nearest'}),100);}}catch(e){this.showError('Search failed')}finally{btn.disabled=false;btn.innerHTML=html}}
showLoading(){const tbody=document.getElementById('resultsBody');document.getElementById('noResults').classList.add('hidden');tbody.innerHTML=Array(5).fill(0).map(()=>'<tr>'+Array(6).fill(0).map(()=>'<td class="px-6 py-4"><div class="skeleton h-4 rounded w-full"></div></td>').join('')+'</tr>').join('');}
displayResults(){const tbody=document.getElementById('resultsBody');const noResults=document.getElementById('noResults');if(this.currentResults.length===0){tbody.innerHTML='';noResults.classList.remove('hidden');return;}noResults.classList.add('hidden');tbody.innerHTML=this.currentResults.map((r,i)=>'<tr class="group hover:bg-gradient-to-r hover:from-indigo-100 hover:to-purple-100 border-b border-gray-300" style="animation:fadeIn .3s ease '+(i*.05)+'s both"><td class="px-6 py-4"><span class="font-mono text-indigo-600 font-bold group-hover:text-indigo-700">'+r.bin+'</span></td><td class="px-6 py-4"><div class="flex items-center gap-2"><i class="fas fa-credit-card text-gray-600 group-hover:text-blue-600"></i><span class="font-medium text-gray-900 group-hover:text-indigo-700">'+r.brand+'</span></div></td><td class="px-6 py-4"><span class="badge '+this.getTypeBadgeClass(r.type)+'"><i class="fas fa-tag"></i>'+r.type+'</span></td><td class="px-6 py-4 text-gray-700 group-hover:text-gray-900">'+(r.category||'-')+'</td><td class="px-6 py-4 text-gray-700 group-hover:text-gray-900">'+(r.issuer||'-')+'</td><td class="px-6 py-4"><span class="px-3 py-1.5 glass rounded-lg text-xs font-mono font-semibold text-gray-700"><i class="fas fa-flag mr-1"></i>'+r.country+'</span></td></tr>').join('');}
getTypeBadgeClass(type){switch(type?.toUpperCase()){case 'CREDIT':return 'badge-credit';case 'DEBIT':return 'badge-debit';case 'PREPAID':return 'badge-prepaid';default:return 'badge-default';}}
updatePagination(p){const start=p.offset+1;const end=Math.min(p.offset+p.limit,p.total);document.getElementById('showingCount').textContent=start+'-'+end;document.getElementById('totalCount').textContent=p.total;const totalPages=Math.max(1,Math.ceil(p.total/p.limit));const currentPage=Math.floor(p.offset/p.limit)+1;const container=document.getElementById('pageNumbers');container.innerHTML='';const addBtn=i=>{const btn=document.createElement('button');btn.textContent=String(i);btn.className=(i===currentPage?'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg':'glass text-gray-700')+' px-4 py-2 rounded-lg text-sm font-semibold hover-lift';btn.onclick=()=>{this.currentPage=i-1;this.search()};container.appendChild(btn);};const addEllipsis=()=>{const span=document.createElement('span');span.textContent='...';span.className='px-2 text-gray-600';container.appendChild(span);};const addRange=(s,e)=>{for(let i=s;i<=e;i++)addBtn(i)};if(totalPages<=10){addRange(1,totalPages);}else{addRange(1,Math.min(5,totalPages));if(currentPage>7)addEllipsis();const midStart=Math.max(currentPage-2,6);const midEnd=Math.min(currentPage+2,totalPages-5);if(midStart<=midEnd)addRange(midStart,midEnd);if(currentPage<totalPages-6)addEllipsis();addRange(Math.max(totalPages-4,6),totalPages);}const prevBtn=document.getElementById('prevBtn');const nextBtn=document.getElementById('nextBtn');prevBtn.disabled=currentPage===1;nextBtn.disabled=currentPage===totalPages;prevBtn.classList.toggle('opacity-50',prevBtn.disabled);prevBtn.classList.toggle('cursor-not-allowed',prevBtn.disabled);nextBtn.classList.toggle('opacity-50',nextBtn.disabled);nextBtn.classList.toggle('cursor-not-allowed',nextBtn.disabled);}
previousPage(){if(this.currentPage>0){this.currentPage--;this.search()}}nextPage(){this.currentPage++;this.search()}jumpToPage(){const val=parseInt(document.getElementById('pageJumpInput').value);if(!isNaN(val)&&val>=1){this.currentPage=val-1;this.search();document.getElementById('pageJumpInput').value='';}}
clearFilters(){document.getElementById('binInput').value='';document.getElementById('binCounter').textContent='374788';['brandFilter','typeFilter','categoryFilter','countryFilter','issuerFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});document.getElementById('limitInput').value='10';this.currentPage=0;this.search();}
async loadDashboard(force=false){const content=document.getElementById('dashContent');if(!force&&content.innerHTML.includes('grid'))return;content.innerHTML='<div class="text-center py-8"><div class="loading inline-block"></div></div>';try{const r=await fetch('/api/dashboard');const d=await r.json();if(d.success){const s=d.data;const topBrands=(s.brands||[]).slice(0,10);const topCountries=(s.countries||[]).slice(0,10);const topTypes=(s.types||[]).slice(0,10);const topCategories=(s.categories||[]).slice(0,10);const topBins=(s.topBins||[]).slice(0,10);content.innerHTML='<div class="grid grid-cols-1 md:grid-cols-4 gap-3 mb-4">'+
'<div class="glass p-4 rounded-xl text-center hover-lift"><i class="fas fa-database text-3xl text-indigo-600 mb-2"></i><div class="text-3xl font-bold text-gray-900">'+(s.totalRecords||0).toLocaleString()+'</div><div class="text-sm text-gray-600">Total BINs</div></div>'+
'<div class="glass p-4 rounded-xl text-center hover-lift"><i class="fas fa-credit-card text-3xl text-blue-600 mb-2"></i><div class="text-3xl font-bold text-gray-900">'+(s.totalCards||0).toLocaleString()+'</div><div class="text-sm text-gray-600">Total Cards</div></div>'+
'<div class="glass p-4 rounded-xl text-center hover-lift"><i class="fas fa-check-circle text-3xl text-green-600 mb-2"></i><div class="text-3xl font-bold text-gray-900">'+(s.liveCards||0).toLocaleString()+'</div><div class="text-sm text-gray-600">Live Cards</div></div>'+
'<div class="glass p-4 rounded-xl text-center hover-lift"><i class="fas fa-times-circle text-3xl text-red-600 mb-2"></i><div class="text-3xl font-bold text-gray-900">'+(s.dieCards||0).toLocaleString()+'</div><div class="text-sm text-gray-600">Expired</div></div>'+
'</div>'+
'<div class="grid grid-cols-1 md:grid-cols-3 gap-4">'+
'<div class="glass p-4 rounded-xl hover-lift"><h3 class="font-bold mb-3 flex items-center gap-2 text-gray-900"><i class="fas fa-credit-card text-blue-600"></i>Top 10 Brands</h3><div class="space-y-2">'+(topBrands.length>0?topBrands.map(b=>'<div class="flex items-center justify-between"><span class="font-semibold text-gray-900">'+(b.brand||'UNKNOWN')+'</span><span class="text-sm text-gray-600">'+(b.count||0).toLocaleString()+'</span></div>').join(''):'<div class="text-gray-600 text-center">No data</div>')+'</div></div>'+
'<div class="glass p-4 rounded-xl hover-lift"><h3 class="font-bold mb-3 flex items-center gap-2 text-gray-900"><i class="fas fa-globe text-green-600"></i>Top 10 Countries</h3><div class="space-y-2">'+(topCountries.length>0?topCountries.map(c=>'<div class="flex items-center justify-between"><span class="font-semibold text-gray-900">'+(c.country||'XX')+'</span><span class="text-sm text-gray-600">'+(c.count||0).toLocaleString()+'</span></div>').join(''):'<div class="text-gray-600 text-center">No data</div>')+'</div></div>'+
'<div class="glass p-4 rounded-xl hover-lift"><h3 class="font-bold mb-3 flex items-center gap-2 text-gray-900"><i class="fas fa-list text-purple-600"></i>Top 10 Types</h3><div class="space-y-2">'+(topTypes.length>0?topTypes.map(t=>'<div class="flex items-center justify-between"><span class="font-semibold text-gray-900">'+(t.type||'UNKNOWN')+'</span><span class="text-sm text-gray-600">'+(t.count||0).toLocaleString()+'</span></div>').join(''):'<div class="text-gray-600 text-center">No data</div>')+'</div></div>'+
'</div>'+
'<div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">'+
'<div class="glass p-4 rounded-xl hover-lift"><h3 class="font-bold mb-3 flex items-center gap-2 text-gray-900"><i class="fas fa-layer-group text-cyan-600"></i>Top 10 Categories</h3><div class="space-y-2">'+(topCategories.length>0?topCategories.map(c=>'<div class="flex items-center justify-between"><span class="font-semibold text-gray-900">'+(c.category||'UNKNOWN')+'</span><span class="text-sm text-gray-600">'+(c.count||0).toLocaleString()+'</span></div>').join(''):'<div class="text-gray-600 text-center">No data</div>')+'</div></div>'+
'<div class="glass p-4 rounded-xl hover-lift"><h3 class="font-bold mb-3 flex items-center gap-2 text-gray-900"><i class="fas fa-hashtag text-orange-600"></i>Top 10 BINs</h3><div class="space-y-2">'+(topBins.length>0?topBins.map(b=>'<div class="flex items-center justify-between"><span class="font-mono font-semibold text-gray-900">'+(b.Bin||b.bin||'')+'</span><span class="text-sm text-gray-600">'+(b.count||0).toLocaleString()+'</span></div>').join(''):'<div class="text-gray-600 text-center">No data</div>')+'</div></div>'+
'</div>';}}catch(e){content.innerHTML='<div class="text-center text-red-400">Failed to load dashboard</div>';}}
copyBinsList(){try{if(!this.currentResults||this.currentResults.length===0){this.showError('No BINs to copy');return;}const binsList=this.currentResults.map(r=>r.bin).join(NL);navigator.clipboard.writeText(binsList).then(()=>{this.showSuccess('Copied '+this.currentResults.length+' BINs to clipboard');}).catch(()=>{const textarea=document.createElement('textarea');textarea.value=binsList;document.body.appendChild(textarea);textarea.select();document.execCommand('copy');document.body.removeChild(textarea);this.showSuccess('Copied '+this.currentResults.length+' BINs to clipboard');});}catch(e){this.showError('Copy failed')}}
async searchBinsForExport(){const btn=document.getElementById('searchBinsBtn');const html=btn.innerHTML;btn.disabled=true;btn.innerHTML='<div class=\"loading inline-block mr-2\"></div>Searching...';try{const status=[];if(document.getElementById('statusUnknown').checked)status.push('unknown');if(document.getElementById('statusLive').checked)status.push('1');if(document.getElementById('statusCT').checked)status.push('2');if(document.getElementById('statusDie').checked)status.push('0');if(status.length===0){this.showError('Please select at least one status');return;}const rawBins=(document.getElementById('cardBinsInput')?.value||'').trim();const bins=rawBins?rawBins.split(',').flatMap(part=>part.split(NL)).map(b=>b.trim()).filter(b=>/^\\d{6}$/.test(b)):[];const params={brand:document.getElementById('cardBrandFilter').value||null,type:document.getElementById('cardTypeFilter').value||null,category:document.getElementById('cardCategoryFilter').value||null,country:document.getElementById('cardCountryFilter').value||null,issuer:document.getElementById('cardIssuerFilter').value.trim()||null,minCards:parseInt(document.getElementById('minCardsInput').value)||10,maxBins:parseInt(document.getElementById('maxBinsInput').value)||10000,status,bins};const r=await fetch('/api/search-bins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params)});const d=await r.json();if(d.success){this.cardExporter.bins=d.bins;this.displayBinResults(d.bins);document.getElementById('cardResultsSection').classList.remove('hidden');document.getElementById('exportOptionsSection').classList.remove('hidden');this.showSuccess('Found '+d.bins.length+' BINs');}else{this.showError(d.error||'Search failed');}}catch(e){this.showError('Search failed: '+e.message);}finally{btn.disabled=false;btn.innerHTML=html}}
displayBinResults(bins){const totalCards=bins.reduce((s,b)=>s+(b.cardCount||0),0);document.getElementById('foundBinsCount').textContent=String(bins.length);document.getElementById('totalCardsCount').textContent=totalCards.toLocaleString();const tbody=document.getElementById('cardResultsBody');tbody.innerHTML=bins.map((b,i)=>'<tr class="group hover:bg-gradient-to-r hover:from-indigo-100 hover:to-purple-100 border-b border-gray-300" style="animation:fadeIn .3s ease '+(i*.02)+'s both"><td class="px-6 py-4"><span class="font-mono text-indigo-600 font-bold">'+b.bin+'</span></td><td class="px-6 py-4 text-gray-900">'+b.brand+'</td><td class="px-6 py-4"><span class="badge '+this.getTypeBadgeClass(b.type)+'">'+b.type+'</span></td><td class="px-6 py-4 text-gray-900">'+(b.category||'-')+'</td><td class="px-6 py-4"><span class="font-mono text-gray-900">'+b.country+'</span></td><td class="px-6 py-4"><span class="font-bold text-gray-900">'+(b.cardCount||0).toLocaleString()+'</span></td><td class="px-6 py-4"><div class="flex items-center gap-2"><div class="w-24 h-2 bg-gray-200 rounded-full overflow-hidden"><div class="h-full bg-gradient-to-r from-green-500 to-emerald-500" style="width:'+(b.liveRate*100).toFixed(0)+'%"></div></div><span class="text-sm font-semibold text-gray-900">'+(b.liveRate*100).toFixed(0)+'%</span></div></td></tr>').join('');}
async startExport(){if(this.cardExporter.bins.length===0){this.showError('No BINs to export');return;}
const cardsPerBinInput=document.querySelector('#cardsPerBinInput');
const cardsPerBinVal=parseInt(cardsPerBinInput.value);
const isFullExport=cardsPerBinVal>=2000;
const totalExpectedCards=this.cardExporter.bins.reduce((s,b)=>s+(isFullExport?b.cardCount:Math.min(b.cardCount,cardsPerBinVal)),0);
const format=document.querySelector('input[name="exportFormat"]:checked').value;
const status=[];if(document.getElementById('statusUnknown').checked)status.push('unknown');if(document.getElementById('statusLive').checked)status.push('1');if(document.getElementById('statusCT').checked)status.push('2');if(document.getElementById('statusDie').checked)status.push('0');
this.cardExporter.cancelExport=false;document.getElementById('exportProgressSection').classList.remove('hidden');document.getElementById('exportResultSection').classList.add('hidden');document.getElementById('exportProgressFill').style.width='0%';document.getElementById('exportedCardsCount').textContent='0';document.getElementById('exportTime').textContent='0';document.getElementById('exportSpeed').textContent='0';const startTime=Date.now();
if(totalExpectedCards>=2000||isFullExport){
  try{
    let totalExported=0;
    for(let i=0;i<this.cardExporter.bins.length;i++){
      if(this.cardExporter.cancelExport){this.showError('Export cancelled');return;}
      const binData=this.cardExporter.bins[i];
      const bin=binData.bin;
      const binTotalCards=binData.cardCount;
      const BATCH_SIZE=10000;
      let binExportedCards=[];
      document.getElementById('exportProgressText').textContent='Exporting BIN '+bin+' ('+(i+1)+'/'+this.cardExporter.bins.length+')...';
      for(let offset=0;offset<binTotalCards;offset+=BATCH_SIZE){
        if(this.cardExporter.cancelExport) break;
        const r=await fetch('/api/export-cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bins:[bin],limit:BATCH_SIZE,offset,status,format,sequential:true})});
        const d=await r.json();
        if(d.success&&d.cards.length>0){
          binExportedCards.push(...d.cards);
          totalExported+=d.cards.length;
          const progress=((i+(offset+d.cards.length)/binTotalCards)/this.cardExporter.bins.length*100).toFixed(0);
          document.getElementById('exportProgressFill').style.width=progress+'%';
          document.getElementById('exportedCardsCount').textContent=totalExported.toLocaleString();
          const elapsed=Math.max(1,Math.floor((Date.now()-startTime)/1000));
          document.getElementById('exportTime').textContent=elapsed;
          document.getElementById('exportSpeed').textContent=Math.floor(totalExported/elapsed);
        } else {
          break;
        }
      }
      if(binExportedCards.length>0){
        const blob=new Blob([binExportedCards.join(NL)],{type:'text/plain'});
        const url=URL.createObjectURL(blob);
        const a=document.createElement('a');
        a.href=url;
        a.download='BIN_'+bin+'_'+binExportedCards.length+'.txt';
        a.style.display='none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        await new Promise(r=>setTimeout(r,500));
      }
    }
    this.showSuccess('Export completed! Files downloaded.');
    document.getElementById('exportProgressSection').classList.add('hidden');
  }catch(e){this.showError('Export failed: '+e.message);}
} else {
  const allCards=[];
  const BATCH_SIZE=10;
  try{for(let i=0;i<this.cardExporter.bins.length;i+=BATCH_SIZE){if(this.cardExporter.cancelExport){this.showError('Export cancelled');return;}const batch=this.cardExporter.bins.slice(i,Math.min(i+BATCH_SIZE,this.cardExporter.bins.length));const batchBins=batch.map(b=>b.bin);
  const r=await fetch('/api/export-cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bins:batchBins,cardsPerBin:cardsPerBinVal,status,format,sequential:false})});
  const d=await r.json();if(d.success){
    allCards.push(...d.cards);
    const progress=((i+batch.length)/this.cardExporter.bins.length*100).toFixed(0);const elapsed=Math.floor((Date.now()-startTime)/1000);const totalCardsExported=allCards.length;const speed=elapsed>0?Math.floor(totalCardsExported/elapsed):0;document.getElementById('exportProgressFill').style.width=progress+'%';document.getElementById('exportProgressText').textContent='Processing '+(i+batch.length)+' / '+this.cardExporter.bins.length+' BINs...';document.getElementById('exportedCardsCount').textContent=totalCardsExported;document.getElementById('exportTime').textContent=elapsed;document.getElementById('exportSpeed').textContent=speed;}}
    document.getElementById('exportOutput').value=allCards.join(NL);document.getElementById('exportResultSection').classList.remove('hidden');document.getElementById('exportProgressSection').classList.add('hidden');this.showSuccess('Exported '+allCards.length+' cards');}catch(e){this.showError('Export failed: '+e.message);}}}
cancelExport(){this.cardExporter.cancelExport=true;document.getElementById('exportProgressSection').classList.add('hidden');}
downloadExport(){const content=document.getElementById('exportOutput').value;if(!content){this.showError('Nothing to download');return;}const blob=new Blob([content],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cards_export_'+Date.now()+'.txt';a.click();URL.revokeObjectURL(url);this.showSuccess('Download started');}
clearCardFilters(){document.getElementById('cardBrandFilter').value='';document.getElementById('cardTypeFilter').value='';document.getElementById('cardCategoryFilter').value='';document.getElementById('cardCountryFilter').value='';document.getElementById('cardIssuerFilter').value='';document.getElementById('minCardsInput').value='10';document.getElementById('cardsPerBinInput').value='50';document.getElementById('maxBinsInput').value='10000';document.getElementById('statusUnknown').checked=true;document.getElementById('statusLive').checked=true;document.getElementById('statusCT').checked=true;document.getElementById('statusDie').checked=false;document.getElementById('cardResultsSection').classList.add('hidden');document.getElementById('exportOptionsSection').classList.add('hidden');document.getElementById('exportResultSection').classList.add('hidden');this.cardExporter.bins=[];}
async normalize(){const input=document.getElementById('normalizeInput').value.trim();if(!input)return this.showError('Please enter cards');const lines=input.split(NL).filter(l=>l.trim());if(lines.length>100000)return this.showError('Maximum 100,000 cards allowed');const btn=document.getElementById('normalizeBtn');const html=btn.innerHTML;btn.disabled=true;btn.innerHTML='<div class="loading inline-block mr-2"></div>Processing...';try{const filterExpired=document.getElementById('filterExpiredCheck').checked;const r=await fetch('/api/normalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cards:lines,filterExpired})});const d=await r.json();if(d.success){document.getElementById('normValid').textContent=d.data.validCount;document.getElementById('normError').textContent=d.data.errorCount;document.getElementById('normalizeOutput').value=d.data.valid.join(NL);document.getElementById('normalizeResult').classList.remove('hidden');if(d.data.errorCount>0){document.getElementById('normalizeErrors').value=d.data.errors.join(NL);document.getElementById('normErrorSection').classList.remove('hidden');}else{document.getElementById('normErrorSection').classList.add('hidden');}this.showSuccess('Normalized '+d.data.validCount+' cards');}}catch(e){this.showError('Normalize failed');}finally{btn.disabled=false;btn.innerHTML=html;}}
handleDupFileUpload(e){const file=e.target.files[0];if(!file)return;if(!file.name.endsWith('.txt')){this.showError('Please select a .txt file');return;}const reader=new FileReader();reader.onload=(event)=>{const content=event.target.result;document.getElementById('dupInput').value=content;const lines=content.split(NL).filter(l=>l.trim());document.getElementById('dupCount').textContent=lines.length;this.showSuccess('Loaded '+lines.length+' cards from file');};reader.readAsText(file);e.target.value='';}
async checkDup(){const input=document.getElementById('dupInput').value.trim();if(!input)return this.showError('Please enter cards');const lines=input.split(NL).filter(l=>l.trim());const btn=document.getElementById('dupBtn');const html=btn.innerHTML;btn.disabled=true;btn.innerHTML='<div class="loading inline-block mr-2"></div>Checking...';const BATCH_SIZE=1000;let allUnique=[];let allDuplicates=[];document.getElementById('dupProgress').classList.remove('hidden');try{for(let i=0;i<lines.length;i+=BATCH_SIZE){const batch=lines.slice(i,Math.min(i+BATCH_SIZE,lines.length));const progress=Math.round(((i+batch.length)/lines.length)*100);document.getElementById('dupProgressFill').style.width=progress+'%';document.getElementById('dupProgressText').textContent='Processing '+(i+batch.length)+' / '+lines.length+'...';const r=await fetch('/api/check-duplicates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cards:batch})});if(!r.ok){const errorText=await r.text();console.error('API Error:',errorText);throw new Error('HTTP '+r.status+': '+errorText.substring(0,100));}const d=await r.json();if(d.success){allUnique.push(...d.data.unique);allDuplicates.push(...d.data.duplicates);}else{throw new Error(d.error||'Unknown error');}if(i+BATCH_SIZE<lines.length){await new Promise(resolve=>setTimeout(resolve,100));}}document.getElementById('dupProgressFill').style.width='100%';document.getElementById('dupProgressText').textContent='Complete!';setTimeout(()=>{document.getElementById('dupProgress').classList.add('hidden');},1000);document.getElementById('dupTotal').textContent=lines.length;document.getElementById('dupUnique').textContent=allUnique.length;document.getElementById('dupDup').textContent=allDuplicates.length;document.getElementById('dupOutput').value=allUnique.join(NL);document.getElementById('dupResult').classList.remove('hidden');if(allDuplicates.length>0){document.getElementById('dupDupOutput').value=allDuplicates.join(NL);document.getElementById('dupDupSection').classList.remove('hidden');}else{document.getElementById('dupDupSection').classList.add('hidden');}this.showSuccess('Found '+allUnique.length+' unique cards');}catch(e){console.error('Check duplicates error:',e);document.getElementById('dupProgress').classList.add('hidden');this.showError('Check failed: '+e.message);}finally{btn.disabled=false;btn.innerHTML=html;}}
handleFileUpload(e){const file=e.target.files[0];if(!file)return;if(!file.name.endsWith('.txt')){this.showError('Please select a .txt file');return;}const reader=new FileReader();reader.onload=(event)=>{const content=event.target.result;document.getElementById('importInput').value=content;const lines=content.split(NL).filter(l=>l.trim());document.getElementById('importCount').textContent=lines.length;this.showSuccess('Loaded '+lines.length+' cards from file');};reader.readAsText(file);e.target.value='';}
async import(){const input=document.getElementById('importInput').value.trim();if(!input)return this.showError('Please enter cards');const lines=input.split(NL).filter(l=>l.trim());if(lines.length>100000)return this.showError('Maximum 100,000 cards allowed');if(!confirm('Import '+lines.length.toLocaleString()+' cards to database?'+NL+NL+'This action cannot be undone.'))return;const btn=document.getElementById('importBtn');const html=btn.innerHTML;btn.disabled=true;btn.innerHTML='<div class="loading inline-block mr-2"></div>Importing...';const BATCH_SIZE=1000;let totalImported=0;let totalErrors=0;const allErrors=[];document.getElementById('importProgress').classList.remove('hidden');try{for(let i=0;i<lines.length;i+=BATCH_SIZE){const batch=lines.slice(i,Math.min(i+BATCH_SIZE,lines.length));const progress=Math.round(((i+batch.length)/lines.length)*100);document.getElementById('importProgressFill').style.width=progress+'%';document.getElementById('importProgressText').textContent='Importing '+(i+batch.length)+' / '+lines.length+' cards...';const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cards:batch})});if(!r.ok){const errorText=await r.text();console.error('API Error:',errorText);throw new Error('HTTP '+r.status+': '+errorText.substring(0,100));}const d=await r.json();if(d.success){totalImported+=d.data.imported||0;totalErrors+=d.data.errorCount||0;if(d.data.errors&&d.data.errors.length>0){allErrors.push(...d.data.errors);}}else{throw new Error(d.error||'Unknown error');}if(i+BATCH_SIZE<lines.length){await new Promise(resolve=>setTimeout(resolve,50));}}document.getElementById('importProgressFill').style.width='100%';document.getElementById('importProgressText').textContent='Complete!';setTimeout(()=>{document.getElementById('importProgress').classList.add('hidden');},1000);document.getElementById('impSuccess').textContent=totalImported;document.getElementById('impError').textContent=totalErrors;document.getElementById('importStats').classList.remove('hidden');if(totalErrors>0){document.getElementById('importErrors').value=allErrors.join(NL);document.getElementById('impErrorSection').classList.remove('hidden');}else{document.getElementById('impErrorSection').classList.add('hidden');}this.showSuccess('Successfully imported '+totalImported.toLocaleString()+' cards');this.loadDashboard(true);}catch(e){console.error('Import error:',e);document.getElementById('importProgress').classList.add('hidden');this.showError('Import failed: '+e.message);}finally{btn.disabled=false;btn.innerHTML=html;}}
copy(id){const el=document.getElementById(id);if(!el.value)return this.showError('Nothing to copy');el.select();document.execCommand('copy');this.showSuccess('Copied to clipboard');}
showError(msg){const t=document.createElement('div');t.className='fixed top-20 right-4 glass p-4 rounded-xl shadow-2xl z-50 fade-in';t.innerHTML='<div class="flex items-center gap-3"><i class="fas fa-exclamation-circle text-red-600 text-xl"></i><div><div class="font-semibold text-red-600">Error</div><div class="text-sm text-gray-700">'+msg+'</div></div></div>';document.body.appendChild(t);setTimeout(()=>{t.style.opacity='0';setTimeout(()=>t.remove(),300)},4000);}
showSuccess(msg){const t=document.createElement('div');t.className='fixed top-20 right-4 glass p-4 rounded-xl shadow-2xl z-50 fade-in';t.innerHTML='<div class="flex items-center gap-3"><i class="fas fa-check-circle text-green-600 text-xl"></i><div><div class="font-semibold text-green-600">Success</div><div class="text-sm text-gray-700">'+msg+'</div></div></div>';document.body.appendChild(t);setTimeout(()=>{t.style.opacity='0';setTimeout(()=>t.remove(),300)},3000);} }
(function(){const boot=()=>{try{new BINLookup();['normalizeInput','dupInput','importInput'].forEach(id=>{const textarea=document.getElementById(id),countId=id==='normalizeInput'?'normalizeCount':id==='dupInput'?'dupCount':'importCount';if(textarea&&countId){textarea.addEventListener('input',function(){const lines=this.value.trim().split(NL).filter(l=>l.trim());document.getElementById(countId).textContent=lines.length.toLocaleString();});}});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();const el=document.getElementById('binInput');if(el)el.focus();}});}catch(e){console.error('Init Error:',e);}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();`;
}
